### ISSUE TITLE
"Original" picocom

### ISSUE THREAD

**Issue by npat-efault** [paulchakravarti/picocom-noexec#1]
Hi,

I'm the original picocom author. 

I'm writing just to let you know that features similar to the ones in your fork have been added to the [latest release of the original picocom](https://github.com/npat-efault/picocom/releases) (along with several other features). While the implementation is not taken from your fork, I added you in the CONTRIBUTORS file mentioning you as the origin of the features.

Thanks for helping make picocom better.
/npat

**Comment by paulc** [comment]
Nick,

Thanks very much for letting me know - it's great to see that the project has been updated. It looked as if it was mostly dormant at the time and the changes were so small so I didn't really expect them to be incorporated. I've added a note to the top of the README pointing people back to your version.

Thanks again for picocom - it's a really great utility.

Paul
